#!/bin/sh

#SBATCH --job-name=goes_eurec4a
#SBATCH --partition=compute
#SBATCH --account=innovation
#SBATCH --time=01:30:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=5GB

module load 2023r1
conda activate gogoesgone_env
python plot_eurec4a_01.py


